server:
  port: 8088

## mysql
#spring.datasource.url:jdbc:mysql://ramgibauk.com:3306/t3?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
#spring.datasource.driverClassName:com.mysql.cj.jdbc.Driver

## mariaDB
spring:
  datasource:
    url: jdbc:mariadb://dev.ramgibauk.com:3306/wiki?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    driverClassName: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1014357240100-0n9j52m6b9ighnl9maot2m5bf8ueo5dc.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
          kakao:
            client-name: kakao
            client-authentication-method: client_secret_post
            client-id: 59cec9efc2fd0250495c88065ffbca5a
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8088/login/oauth2/code/kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id